# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HitchhikerSource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16HitchhikerSource.proto\x12\x10hitchhikersource\"\x0e\n\x0c\x45mptyRequest\"%\n\x10SourceIdResponse\x12\x11\n\tsource_id\x18\x01 \x01(\t\"B\n\x15\x43lientDownloadRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65stination_id\x18\x02 \x01(\t\"E\n\x14\x44ownloadListResponse\x12-\n\tfile_list\x18\x01 \x03(\x0b\x32\x1a.hitchhikersource.FileList\"A\n\x08\x46ileList\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t\";\n\x13\x44ownloadFileRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\tfile_list\x18\x02 \x03(\t\"<\n\x14\x44ownloadFileResponse\x12$\n\x04\x66ile\x18\x01 \x03(\x0b\x32\x16.hitchhikersource.File\"P\n\x04\x46ile\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t\x12\x11\n\tfile_blob\x18\x04 \x01(\x0c\"U\n\x15\x43lientDeliveryRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65stination_id\x18\x02 \x01(\t\x12\x11\n\tfile_list\x18\x03 \x03(\t\"(\n\x16\x44\x65liveryStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x89\x03\n\x10HitchhikerSource\x12Q\n\x0bGetSourceId\x12\x1e.hitchhikersource.EmptyRequest\x1a\".hitchhikersource.SourceIdResponse\x12_\n\x0cGetDownloads\x12\'.hitchhikersource.ClientDownloadRequest\x1a&.hitchhikersource.DownloadListResponse\x12]\n\x0c\x44ownloadFile\x12%.hitchhikersource.DownloadFileRequest\x1a&.hitchhikersource.DownloadFileResponse\x12\x62\n\rMarkDelivered\x12\'.hitchhikersource.ClientDeliveryRequest\x1a(.hitchhikersource.DeliveryStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HitchhikerSource_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTYREQUEST']._serialized_start=44
  _globals['_EMPTYREQUEST']._serialized_end=58
  _globals['_SOURCEIDRESPONSE']._serialized_start=60
  _globals['_SOURCEIDRESPONSE']._serialized_end=97
  _globals['_CLIENTDOWNLOADREQUEST']._serialized_start=99
  _globals['_CLIENTDOWNLOADREQUEST']._serialized_end=165
  _globals['_DOWNLOADLISTRESPONSE']._serialized_start=167
  _globals['_DOWNLOADLISTRESPONSE']._serialized_end=236
  _globals['_FILELIST']._serialized_start=238
  _globals['_FILELIST']._serialized_end=303
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=305
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=364
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=366
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=426
  _globals['_FILE']._serialized_start=428
  _globals['_FILE']._serialized_end=508
  _globals['_CLIENTDELIVERYREQUEST']._serialized_start=510
  _globals['_CLIENTDELIVERYREQUEST']._serialized_end=595
  _globals['_DELIVERYSTATUSRESPONSE']._serialized_start=597
  _globals['_DELIVERYSTATUSRESPONSE']._serialized_end=637
  _globals['_HITCHHIKERSOURCE']._serialized_start=640
  _globals['_HITCHHIKERSOURCE']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
